name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "Changes"
    labels:
      - "enhancement"
  - title: "New Features"
    labels:
      - "feature :sparkles:"
  - title: "Bug Fixes"
    labels:
      - "bug :bug:"
  - title: "Documentation"
    labels:
      - "documentation :memo:"
  - title: "Tooling"
    labels:
      - "tooling :wrench:"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No changes"
template: |
  ## Release Notes

  ${{#if NEW_FEATURES}}
  ### New Features
  $NEW_FEATURES
  ${{/if}}

  ${{#if CHANGES}}
  ### Changes
  $CHANGES
  ${{/if}}

  ${{#if BUG_FIXES}}
  ### Bug Fixes
  $BUG_FIXES
  ${{/if}}

  ${{#if DOCUMENTATION}}
  ### Documentation
  $DOCUMENTATION
  ${{/if}}

  ${{#if TOOLING}}
  ### Tooling
  $TOOLING
  ${{/if}}

  ${{#if CONTRIBUTORS}}
  ### Contributors
  $CONTRIBUTORS
  ${{/if}}
